### ISSUE TITLE
Crash when adding new student

### ISSUE THREAD

**Issue by jakobkogler** [jakobkogler/pk-tool#3]
```
Traceback (most recent call last):
  File "/home/jakob/GitHub/PK_Uebungstool/pk-tool.py", line 37, in <lambda>
    self.table_widget.cellChanged.connect(lambda: self.write_file(savefile=True))
  File "/home/jakob/GitHub/PK_Uebungstool/pk-tool.py", line 220, in write_file
    if self.table_widget.item(idx, 1).text():
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by jakobkogler** [comment]
Fixed by 0ffc77782d46c3a2bf15d29cdaf2064ade7b82db
